# Generated by Django 3.2.25 on 2024-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='google_id_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
