# Generated by Django 3.2.25 on 2024-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
