# Generated by Django 3.2.25 on 2024-05-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0002_app_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.element')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='Workflow.event')),
            ],
        ),
    ]
