# Generated by Django 3.2.25 on 2024-05-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
        ('Workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventsbyapp', to='App.app'),
        ),
    ]
