# Generated by Django 3.2.25 on 2024-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0002_event_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='champs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
