# Generated by Django 3.2.25 on 2024-05-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
        ('Workflow', '0004_action_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='App.element'),
        ),
    ]
