# Generated by Django 3.2.25 on 2024-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
        ('Workflow', '0005_action_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='element',
        ),
        migrations.AddField(
            model_name='action',
            name='elements',
            field=models.ManyToManyField(null=True, related_name='actionselements', to='App.Element'),
        ),
    ]
