# Generated by Django 3.2.25 on 2024-05-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
        ('Workflow', '0006_auto_20240528_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='champs',
        ),
        migrations.RemoveField(
            model_name='action',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='action',
            name='table_name',
        ),
        migrations.CreateModel(
            name='ElementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champs', models.CharField(max_length=100, null=True)),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workflow.action')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.element')),
            ],
        ),
    ]
