# Generated by Django 3.2.25 on 2024-05-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
        ('Workflow', '0007_auto_20240528_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementaction',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Workflow.action'),
        ),
        migrations.AlterField(
            model_name='elementaction',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.element'),
        ),
    ]
