# Generated by Django 3.2.25 on 2024-05-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
        ('Workflow', '0008_auto_20240528_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screensactions', to='App.screen'),
        ),
    ]
