# Generated by Django 3.2.25 on 2024-04-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0001_initial'),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='database',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Databases.database'),
        ),
    ]
