# Generated by Django 3.2.25 on 2024-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_app_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
