# Generated by Django 3.2.25 on 2024-06-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_element_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='textcolor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
