# Generated by Django 3.2.25 on 2024-04-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_relation', models.CharField(max_length=100)),
                ('type_relation', models.CharField(choices=[('OneToOne', 'OneToOne'), ('OneToMany', 'OneToMany'), ('ManyToOne', 'ManyToOne'), ('ManyToMany', 'ManyToMany')], max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_entity', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='Databases.database')),
                ('relations', models.ManyToManyField(null=True, related_name='entities', to='Databases.Relation')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attribute', models.CharField(max_length=100)),
                ('type_attribute', models.CharField(max_length=100)),
                ('length', models.IntegerField(null=True)),
                ('required', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=1)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='Databases.entity')),
            ],
        ),
    ]
