# Generated by Django 3.2.25 on 2024-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0003_alter_attribute_listfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='listField',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], default='N', max_length=1),
        ),
    ]
